export { default as HomeView } from './HomeView.vue';
export { default as LoginView } from './LoginView.vue';
export { default as InsertTitleView } from './titles/InsertTitleView.vue';
export { default as AdminView } from './admin/AdminIndex.vue';
export { default as InsertReviewView } from './admin/reviews/InsertReviewView.vue';
export { default as ReviewView } from './reviews/ReviewView.vue';
export { default as ManageReviews } from './admin/reviews/ManageReviews.vue'
export { default as MetaDataView } from './admin/MetaDataView.vue'
export { default as UpdateReviewView } from './admin/reviews/UpdateReviewView.vue'